name: CI
on: push

jobs:
  Job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxelib --quiet install openfl
          haxelib --quiet install extension-networking

      - name: Formatting
        run: haxelib run openfl run linux -s ./source

  deploy:
    name: Docker container with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run container
      run: docker-compose up -d 
    
    - uses: luisboto/ngrok-tunnel-action@<VERSION>
      with:
        timeout: 8h
        port: 8888
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
        tunnel_type: tcp
        save_url_to_filename: tunnelURL.md
